#ifndef hhtree_HH
#include <TBranch.h> 
#include <TTree.h> 
#include <TH1F.h> 
#include <TFile.h> 
#include <TBits.h> 
#include <vector> 
#include <unistd.h> 
using namespace std; 

class hhtree{
 private:
 protected:
   unsigned int index;
   unsigned int run_;
   TBranch *run_branch;
   bool run_isLoaded;
   unsigned int luminosityBlock_;
   TBranch *luminosityBlock_branch;
   bool luminosityBlock_isLoaded;
   unsigned long int event_;
   TBranch *event_branch;
   bool event_isLoaded;
   float genWeight_;
   TBranch *genWeight_branch;
   bool genWeight_isLoaded;
   float ChsMET_phi_;
   TBranch *ChsMET_phi_branch;
   bool ChsMET_phi_isLoaded;
   float ChsMET_pt_;
   TBranch *ChsMET_pt_branch;
   bool ChsMET_pt_isLoaded;
   float ChsMET_sumEt_;
   TBranch *ChsMET_sumEt_branch;
   bool ChsMET_sumEt_isLoaded;
   float h_gen_pt_[10];
   TBranch *h_gen_pt_branch;
   bool h_gen_pt_isLoaded;
   float h_gen_eta_[10];
   TBranch *h_gen_eta_branch;
   bool h_gen_eta_isLoaded;
   float h_gen_phi_[10];
   TBranch *h_gen_phi_branch;
   bool h_gen_phi_isLoaded;
   unsigned int hh_fatjet_idx_[10];
   TBranch *hh_fatjet_idx_branch;
   bool hh_fatjet_idx_isLoaded;
   unsigned int nFatJet_;
   TBranch *nFatJet_branch;
   bool nFatJet_isLoaded;
   float FatJet_LSmsoftdrop_[10];
   TBranch *FatJet_LSmsoftdrop_branch;
   bool FatJet_LSmsoftdrop_isLoaded;
   float FatJet_LSn2b1_[10];
   TBranch *FatJet_LSn2b1_branch;
   bool FatJet_LSn2b1_isLoaded;
   float FatJet_LSn3b1_[10];
   TBranch *FatJet_LSn3b1_branch;
   bool FatJet_LSn3b1_isLoaded;
   float FatJet_LSpt_[10];
   TBranch *FatJet_LSpt_branch;
   bool FatJet_LSpt_isLoaded;
   float FatJet_LSrawmsoftdrop_[10];
   TBranch *FatJet_LSrawmsoftdrop_branch;
   bool FatJet_LSrawmsoftdrop_isLoaded;
   float FatJet_LSsubJet1btagDeepB_[10];
   TBranch *FatJet_LSsubJet1btagDeepB_branch;
   bool FatJet_LSsubJet1btagDeepB_isLoaded;
   float FatJet_LSsubJet2btagDeepB_[10];
   TBranch *FatJet_LSsubJet2btagDeepB_branch;
   bool FatJet_LSsubJet2btagDeepB_isLoaded;
   float FatJet_LStau1_[10];
   TBranch *FatJet_LStau1_branch;
   bool FatJet_LStau1_isLoaded;
   float FatJet_LStau2_[10];
   TBranch *FatJet_LStau2_branch;
   bool FatJet_LStau2_isLoaded;
   float FatJet_LStau3_[10];
   TBranch *FatJet_LStau3_branch;
   bool FatJet_LStau3_isLoaded;
   float FatJet_LStau4_[10];
   TBranch *FatJet_LStau4_branch;
   bool FatJet_LStau4_isLoaded;
   float FatJet_area_[10];
   TBranch *FatJet_area_branch;
   bool FatJet_area_isLoaded;
   float FatJet_btagDDBvL_[10];
   TBranch *FatJet_btagDDBvL_branch;
   bool FatJet_btagDDBvL_isLoaded;
   float FatJet_btagDDCvB_[10];
   TBranch *FatJet_btagDDCvB_branch;
   bool FatJet_btagDDCvB_isLoaded;
   float FatJet_btagDDCvL_[10];
   TBranch *FatJet_btagDDCvL_branch;
   bool FatJet_btagDDCvL_isLoaded;
   float FatJet_btagHbb_[10];
   TBranch *FatJet_btagHbb_branch;
   bool FatJet_btagHbb_isLoaded;
   float FatJet_dRLep_[10];
   TBranch *FatJet_dRLep_branch;
   bool FatJet_dRLep_isLoaded;
   float FatJet_deepTagHbb_[10];
   TBranch *FatJet_deepTagHbb_branch;
   bool FatJet_deepTagHbb_isLoaded;
   float FatJet_deepTagHcc_[10];
   TBranch *FatJet_deepTagHcc_branch;
   bool FatJet_deepTagHcc_isLoaded;
   float FatJet_deepTagHqqqq_[10];
   TBranch *FatJet_deepTagHqqqq_branch;
   bool FatJet_deepTagHqqqq_isLoaded;
   float FatJet_deepTagMDHbb_[10];
   TBranch *FatJet_deepTagMDHbb_branch;
   bool FatJet_deepTagMDHbb_isLoaded;
   float FatJet_deepTagMDHcc_[10];
   TBranch *FatJet_deepTagMDHcc_branch;
   bool FatJet_deepTagMDHcc_isLoaded;
   float FatJet_deepTagMDHqqqq_[10];
   TBranch *FatJet_deepTagMDHqqqq_branch;
   bool FatJet_deepTagMDHqqqq_isLoaded;
   float FatJet_deepTagMDQCDbb_[10];
   TBranch *FatJet_deepTagMDQCDbb_branch;
   bool FatJet_deepTagMDQCDbb_isLoaded;
   float FatJet_deepTagMDQCDcc_[10];
   TBranch *FatJet_deepTagMDQCDcc_branch;
   bool FatJet_deepTagMDQCDcc_isLoaded;
   float FatJet_deepTagMDWcq_[10];
   TBranch *FatJet_deepTagMDWcq_branch;
   bool FatJet_deepTagMDWcq_isLoaded;
   float FatJet_deepTagMDWqq_[10];
   TBranch *FatJet_deepTagMDWqq_branch;
   bool FatJet_deepTagMDWqq_isLoaded;
   float FatJet_deepTagMDZbb_[10];
   TBranch *FatJet_deepTagMDZbb_branch;
   bool FatJet_deepTagMDZbb_isLoaded;
   float FatJet_deepTagMDZcc_[10];
   TBranch *FatJet_deepTagMDZcc_branch;
   bool FatJet_deepTagMDZcc_isLoaded;
   float FatJet_deepTagMDZqq_[10];
   TBranch *FatJet_deepTagMDZqq_branch;
   bool FatJet_deepTagMDZqq_isLoaded;
   float FatJet_deepTagQCDbb_[10];
   TBranch *FatJet_deepTagQCDbb_branch;
   bool FatJet_deepTagQCDbb_isLoaded;
   float FatJet_deepTagQCDcc_[10];
   TBranch *FatJet_deepTagQCDcc_branch;
   bool FatJet_deepTagQCDcc_isLoaded;
   float FatJet_deepTagWcq_[10];
   TBranch *FatJet_deepTagWcq_branch;
   bool FatJet_deepTagWcq_isLoaded;
   float FatJet_deepTagWqq_[10];
   TBranch *FatJet_deepTagWqq_branch;
   bool FatJet_deepTagWqq_isLoaded;
   float FatJet_deepTagZbb_[10];
   TBranch *FatJet_deepTagZbb_branch;
   bool FatJet_deepTagZbb_isLoaded;
   float FatJet_deepTagZcc_[10];
   TBranch *FatJet_deepTagZcc_branch;
   bool FatJet_deepTagZcc_isLoaded;
   float FatJet_deepTagZqq_[10];
   TBranch *FatJet_deepTagZqq_branch;
   bool FatJet_deepTagZqq_isLoaded;
   float FatJet_eta_[10];
   TBranch *FatJet_eta_branch;
   bool FatJet_eta_isLoaded;
   float FatJet_lsf3_[10];
   TBranch *FatJet_lsf3_branch;
   bool FatJet_lsf3_isLoaded;
   float FatJet_mass_[10];
   TBranch *FatJet_mass_branch;
   bool FatJet_mass_isLoaded;
   float FatJet_msoftdrop_[10];
   TBranch *FatJet_msoftdrop_branch;
   bool FatJet_msoftdrop_isLoaded;
   float FatJet_n2b1_[10];
   TBranch *FatJet_n2b1_branch;
   bool FatJet_n2b1_isLoaded;
   float FatJet_n3b1_[10];
   TBranch *FatJet_n3b1_branch;
   bool FatJet_n3b1_isLoaded;
   float FatJet_phi_[10];
   TBranch *FatJet_phi_branch;
   bool FatJet_phi_isLoaded;
   float FatJet_pt_[10];
   TBranch *FatJet_pt_branch;
   bool FatJet_pt_isLoaded;
   float FatJet_rawFactor_[10];
   TBranch *FatJet_rawFactor_branch;
   bool FatJet_rawFactor_isLoaded;
   float FatJet_rawmsoftdrop_[10];
   TBranch *FatJet_rawmsoftdrop_branch;
   bool FatJet_rawmsoftdrop_isLoaded;
   float FatJet_tau1_[10];
   TBranch *FatJet_tau1_branch;
   bool FatJet_tau1_isLoaded;
   float FatJet_tau2_[10];
   TBranch *FatJet_tau2_branch;
   bool FatJet_tau2_isLoaded;
   float FatJet_tau3_[10];
   TBranch *FatJet_tau3_branch;
   bool FatJet_tau3_isLoaded;
   float FatJet_tau4_[10];
   TBranch *FatJet_tau4_branch;
   bool FatJet_tau4_isLoaded;
   int FatJet_electronIdx3SJ_[10];
   TBranch *FatJet_electronIdx3SJ_branch;
   bool FatJet_electronIdx3SJ_isLoaded;
   int FatJet_idLep_[10];
   TBranch *FatJet_idLep_branch;
   bool FatJet_idLep_isLoaded;
   int FatJet_jetId_[10];
   TBranch *FatJet_jetId_branch;
   bool FatJet_jetId_isLoaded;
   int FatJet_muonIdx3SJ_[10];
   TBranch *FatJet_muonIdx3SJ_branch;
   bool FatJet_muonIdx3SJ_isLoaded;
   int FatJet_nBHadrons_[10];
   TBranch *FatJet_nBHadrons_branch;
   bool FatJet_nBHadrons_isLoaded;
   int FatJet_nCHadrons_[10];
   TBranch *FatJet_nCHadrons_branch;
   bool FatJet_nCHadrons_isLoaded;
   int FatJet_nPFConstituents_[10];
   TBranch *FatJet_nPFConstituents_branch;
   bool FatJet_nPFConstituents_isLoaded;
   int FatJet_subJetIdx1_[10];
   TBranch *FatJet_subJetIdx1_branch;
   bool FatJet_subJetIdx1_isLoaded;
   int FatJet_subJetIdx2_[10];
   TBranch *FatJet_subJetIdx2_branch;
   bool FatJet_subJetIdx2_isLoaded;
   bool FatJet_Hmatch_[10];
   TBranch *FatJet_Hmatch_branch;
   bool FatJet_Hmatch_isLoaded;
   int FatJet_HgenIdx_[10];
   TBranch *FatJet_HgenIdx_branch;
   bool FatJet_HgenIdx_isLoaded;
   float FatJet_HminDR_[10];
   TBranch *FatJet_HminDR_branch;
   bool FatJet_HminDR_isLoaded;
   bool HLT_PFHT1050_;
   TBranch *HLT_PFHT1050_branch;
   bool HLT_PFHT1050_isLoaded;
   bool HLT_AK8PFJet360_TrimMass30_;
   TBranch *HLT_AK8PFJet360_TrimMass30_branch;
   bool HLT_AK8PFJet360_TrimMass30_isLoaded;
   bool HLT_AK8PFJet380_TrimMass30_;
   TBranch *HLT_AK8PFJet380_TrimMass30_branch;
   bool HLT_AK8PFJet380_TrimMass30_isLoaded;
   bool HLT_AK8PFJet400_TrimMass30_;
   TBranch *HLT_AK8PFJet400_TrimMass30_branch;
   bool HLT_AK8PFJet400_TrimMass30_isLoaded;
   bool HLT_AK8PFJet420_TrimMass30_;
   TBranch *HLT_AK8PFJet420_TrimMass30_branch;
   bool HLT_AK8PFJet420_TrimMass30_isLoaded;
   bool HLT_AK8PFHT800_TrimMass50_;
   TBranch *HLT_AK8PFHT800_TrimMass50_branch;
   bool HLT_AK8PFHT800_TrimMass50_isLoaded;
   bool HLT_PFJet500_;
   TBranch *HLT_PFJet500_branch;
   bool HLT_PFJet500_isLoaded;
   bool HLT_AK8PFJet500_;
   TBranch *HLT_AK8PFJet500_branch;
   bool HLT_AK8PFJet500_isLoaded;
   bool HLT_AK8PFJet330_TrimMass30_PFAK8BTagDeepCSV_p17_;
   TBranch *HLT_AK8PFJet330_TrimMass30_PFAK8BTagDeepCSV_p17_branch;
   bool HLT_AK8PFJet330_TrimMass30_PFAK8BTagDeepCSV_p17_isLoaded;
   bool HLT_AK8PFJet330_TrimMass30_PFAK8BTagDeepCSV_p1_;
   TBranch *HLT_AK8PFJet330_TrimMass30_PFAK8BTagDeepCSV_p1_branch;
   bool HLT_AK8PFJet330_TrimMass30_PFAK8BTagDeepCSV_p1_isLoaded;
   bool HLT_AK8PFJet330_PFAK8BTagCSV_p17_;
   TBranch *HLT_AK8PFJet330_PFAK8BTagCSV_p17_branch;
   bool HLT_AK8PFJet330_PFAK8BTagCSV_p17_isLoaded;
   float hh_pt_;
   TBranch *hh_pt_branch;
   bool hh_pt_isLoaded;
   float hh_eta_;
   TBranch *hh_eta_branch;
   bool hh_eta_isLoaded;
   float hh_phi_;
   TBranch *hh_phi_branch;
   bool hh_phi_isLoaded;
   float hh_mass_;
   TBranch *hh_mass_branch;
   bool hh_mass_isLoaded;
   float hh_gen_pt_;
   TBranch *hh_gen_pt_branch;
   bool hh_gen_pt_isLoaded;
   float hh_gen_eta_;
   TBranch *hh_gen_eta_branch;
   bool hh_gen_eta_isLoaded;
   float hh_gen_phi_;
   TBranch *hh_gen_phi_branch;
   bool hh_gen_phi_isLoaded;
   float hh_gen_mass_;
   TBranch *hh_gen_mass_branch;
   bool hh_gen_mass_isLoaded;
   unsigned int nElectron_;
   TBranch *nElectron_branch;
   bool nElectron_isLoaded;
   float Electron_pt_[10];
   TBranch *Electron_pt_branch;
   bool Electron_pt_isLoaded;
   float Electron_eta_[10];
   TBranch *Electron_eta_branch;
   bool Electron_eta_isLoaded;
   float Electron_phi_[10];
   TBranch *Electron_phi_branch;
   bool Electron_phi_isLoaded;
   int Electron_charge_[10];
   TBranch *Electron_charge_branch;
   bool Electron_charge_isLoaded;
   bool Electron_mvaFall17V2Iso_WP80_[10];
   TBranch *Electron_mvaFall17V2Iso_WP80_branch;
   bool Electron_mvaFall17V2Iso_WP80_isLoaded;
   bool Electron_mvaFall17V2Iso_WP90_[10];
   TBranch *Electron_mvaFall17V2Iso_WP90_branch;
   bool Electron_mvaFall17V2Iso_WP90_isLoaded;
   bool Electron_mvaFall17V2Iso_WPL_[10];
   TBranch *Electron_mvaFall17V2Iso_WPL_branch;
   bool Electron_mvaFall17V2Iso_WPL_isLoaded;
   unsigned int nMuon_;
   TBranch *nMuon_branch;
   bool nMuon_isLoaded;
   float Muon_pt_[10];
   TBranch *Muon_pt_branch;
   bool Muon_pt_isLoaded;
   float Muon_eta_[10];
   TBranch *Muon_eta_branch;
   bool Muon_eta_isLoaded;
   float Muon_phi_[10];
   TBranch *Muon_phi_branch;
   bool Muon_phi_isLoaded;
   int Muon_charge_[10];
   TBranch *Muon_charge_branch;
   bool Muon_charge_isLoaded;
   bool Muon_looseId_[10];
   TBranch *Muon_looseId_branch;
   bool Muon_looseId_isLoaded;
   bool Muon_mediumId_[10];
   TBranch *Muon_mediumId_branch;
   bool Muon_mediumId_isLoaded;
   bool Muon_tightId_[10];
   TBranch *Muon_tightId_branch;
   bool Muon_tightId_isLoaded;
   float weight_;
   TBranch *weight_branch;
   bool weight_isLoaded;
 
 
 public:
   void Init(TTree * tree);
   void GetEntry(unsigned int idx);
   void LoadAllBranches();
   const unsigned int &run();
   const unsigned int &luminosityBlock();
   const unsigned long int &event();
   const float &genWeight();
   const float &ChsMET_phi();
   const float &ChsMET_pt();
   const float &ChsMET_sumEt();
   const float *h_gen_pt();
   const float *h_gen_eta();
   const float *h_gen_phi();
   const unsigned int *hh_fatjet_idx();
   const unsigned int &nFatJet();
   const float *FatJet_LSmsoftdrop();
   const float *FatJet_LSn2b1();
   const float *FatJet_LSn3b1();
   const float *FatJet_LSpt();
   const float *FatJet_LSrawmsoftdrop();
   const float *FatJet_LSsubJet1btagDeepB();
   const float *FatJet_LSsubJet2btagDeepB();
   const float *FatJet_LStau1();
   const float *FatJet_LStau2();
   const float *FatJet_LStau3();
   const float *FatJet_LStau4();
   const float *FatJet_area();
   const float *FatJet_btagDDBvL();
   const float *FatJet_btagDDCvB();
   const float *FatJet_btagDDCvL();
   const float *FatJet_btagHbb();
   const float *FatJet_dRLep();
   const float *FatJet_deepTagHbb();
   const float *FatJet_deepTagHcc();
   const float *FatJet_deepTagHqqqq();
   const float *FatJet_deepTagMDHbb();
   const float *FatJet_deepTagMDHcc();
   const float *FatJet_deepTagMDHqqqq();
   const float *FatJet_deepTagMDQCDbb();
   const float *FatJet_deepTagMDQCDcc();
   const float *FatJet_deepTagMDWcq();
   const float *FatJet_deepTagMDWqq();
   const float *FatJet_deepTagMDZbb();
   const float *FatJet_deepTagMDZcc();
   const float *FatJet_deepTagMDZqq();
   const float *FatJet_deepTagQCDbb();
   const float *FatJet_deepTagQCDcc();
   const float *FatJet_deepTagWcq();
   const float *FatJet_deepTagWqq();
   const float *FatJet_deepTagZbb();
   const float *FatJet_deepTagZcc();
   const float *FatJet_deepTagZqq();
   const float *FatJet_eta();
   const float *FatJet_lsf3();
   const float *FatJet_mass();
   const float *FatJet_msoftdrop();
   const float *FatJet_n2b1();
   const float *FatJet_n3b1();
   const float *FatJet_phi();
   const float *FatJet_pt();
   const float *FatJet_rawFactor();
   const float *FatJet_rawmsoftdrop();
   const float *FatJet_tau1();
   const float *FatJet_tau2();
   const float *FatJet_tau3();
   const float *FatJet_tau4();
   const int *FatJet_electronIdx3SJ();
   const int *FatJet_idLep();
   const int *FatJet_jetId();
   const int *FatJet_muonIdx3SJ();
   const int *FatJet_nBHadrons();
   const int *FatJet_nCHadrons();
   const int *FatJet_nPFConstituents();
   const int *FatJet_subJetIdx1();
   const int *FatJet_subJetIdx2();
   const bool *FatJet_Hmatch();
   const int *FatJet_HgenIdx();
   const float *FatJet_HminDR();
   const bool &HLT_PFHT1050();
   const bool &HLT_AK8PFJet360_TrimMass30();
   const bool &HLT_AK8PFJet380_TrimMass30();
   const bool &HLT_AK8PFJet400_TrimMass30();
   const bool &HLT_AK8PFJet420_TrimMass30();
   const bool &HLT_AK8PFHT800_TrimMass50();
   const bool &HLT_PFJet500();
   const bool &HLT_AK8PFJet500();
   const bool &HLT_AK8PFJet330_TrimMass30_PFAK8BTagDeepCSV_p17();
   const bool &HLT_AK8PFJet330_TrimMass30_PFAK8BTagDeepCSV_p1();
   const bool &HLT_AK8PFJet330_PFAK8BTagCSV_p17();
   const float &hh_pt();
   const float &hh_eta();
   const float &hh_phi();
   const float &hh_mass();
   const float &hh_gen_pt();
   const float &hh_gen_eta();
   const float &hh_gen_phi();
   const float &hh_gen_mass();
   const unsigned int &nElectron();
   const float *Electron_pt();
   const float *Electron_eta();
   const float *Electron_phi();
   const int *Electron_charge();
   const bool *Electron_mvaFall17V2Iso_WP80();
   const bool *Electron_mvaFall17V2Iso_WP90();
   const bool *Electron_mvaFall17V2Iso_WPL();
   const unsigned int &nMuon();
   const float *Muon_pt();
   const float *Muon_eta();
   const float *Muon_phi();
   const int *Muon_charge();
   const bool *Muon_looseId();
   const bool *Muon_mediumId();
   const bool *Muon_tightId();
   const float &weight();
};   

#ifndef __CINT__   
extern hhtree hh;   
#endif   

#endif   
